name: .NET 5 CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: .NET 5 Application
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.101' # Check for latest at link at .NET 5 download page
      - run: dotnet build
#       - run: dotnet test 

      

#       - name: Sonarscanner for dotnet
#         uses: Secbyte/dotnet-sonarscanner@v2.3
#         with:
#           buildCommand: dotnet build .
#           testCommand: dotnet test .
#           projectKey: Emitch1202_Dotnet-Test
#           projectName: Dotnet-Test
#           sonarOrganisation: emitch1202
#           beginArguments: >
#             /d:sonar.verbose="true"
#             /d:sonar.cs.opencover.reportsPaths='"/path/to/coverage.xml","/path/to/coverage.2.xml"'
#             /d:sonar.coverage.exclusions='"**/*.cs","**/*.md"'
#         env:
#           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
