name: .NET 5 CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    name: .NET 5 Application
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.101' # Check for latest at link at .NET 5 download page
      - run: dotnet build
#       - run: dotnet test 

      
      - name: SonarScanner for .NET 5 with pull request decoration support
        uses: highbyte/sonarscan-dotnet@2.0
        with:
        # The key of the SonarQube project
          sonarProjectKey: Emitch1202_Dotnet-Test
        # The name of the SonarQube project
          sonarProjectName:  Dotnet-Test
        # The name of the SonarQube organization in SonarCloud. For hosted SonarQube, skip this setting.
          sonarOrganization: emitch1202
          dotnetDisableTests: false
          dotnetBuildArguments: .
          dotnetTestArguments: . --logger trx --collect:"XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=opencover
v

        env:
         SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
